### ISSUE TITLE
I was just about to look for a nice logging tool...

### ISSUE THREAD

**Issue by mikeerickson** [ShardulNalegave/signale.py#2]
And I recalled seeing this somewhere (can't remember where) but I saved the link and the name was catchy so I could remember.  

Longtime Node/JS developer, written many many CLIs and wanted to try out Python for next CLI tool.

Thanks!

**Comment by ShardulNalegave** [comment]
I was in the same situation. Thats what made me build it.
Always ready to help! 😄 😄 😄
